name: Lint

on: push

jobs:
  ruff:
    runs-on: ubuntu-24.04

    env:
      RUFF_OUTPUT_FORMAT: github

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Ruff Formatter
        run: uv run ruff format --diff .

      - name: Ruff Linter
        run: uv run ruff check .

  mypy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: mypy
        run: uv run mypy .
